### PR TITLE
Don't parse kubectl commandline with flag.Parse()

### LINKED ISSUE #8: global options are not parsed by kuberlr
Commands like

```shell
kubectl -n namespace create -f file.yaml
```

are failing if kubectl points to kuberlr. you need to write

```shell
kubectl create -n namespace -f file.yaml
```

instead. it would be good if all the global options (as visible via `kubectl options`) would be supported and forwarded.

### PR DESCRIPTION
**Pull request by jandubois**
It fails unless *all* kubectl global flags are defined as well.

Use manual parsing to just search for `--kubeconfig` option instead.

Fixes #8

### CODE REVIEW

**Comment by jandubois** [comment]
The PR is not correct; I have changed it to Draft status for now

File: internal/kubehelper/client.go [hunk 1]
```diff
@@ -11,8 +11,15 @@ import (
 
 func createKubeClient(timeout int64) (*kubernetes.Clientset, error) {
 	var cliKubeconfig string
-	flag.StringVar(&cliKubeconfig, "kubeconfig", "", "absolute path to the kubeconfig file")
-	flag.Parse()
+	for i := 1; i < len(os.Args)-1; i++ {
+		if os.Args[i] == "--kubeconfig" {
```
Comment (mook-as) [inline internal/kubehelper/client.go:15]: This is incorrect: I can do `kubectl --kubeconfig=/path/to/file` too, so you'll also need to match that.  Luckily, it's not a prefix match, so we don't need to worry about `kubectl --kubeconfi /path/to/file` (note missing `g`).

Confirmed by testing with `kubectl --kubeconfig /dev/null config current-context` (and  variations) and noting the difference in error messages.

**Review by mook-as — CHANGES_REQUESTED** [review]

File: internal/kubehelper/client.go (hunk 1 above)
Comment (jandubois) [reply internal/kubehelper/client.go:16]: > This is incorrect: I can do `kubectl --kubeconfig=/path/to/file` too, so you'll also need to match that.

Thanks for catching that! I've updated the PR; please review again!

File: internal/kubehelper/client.go [hunk 2]
```diff
@@ -11,8 +12,19 @@ import (
...
+			cliKubeconfig = os.Args[i+1]
+			break
```
Comment (mook-as) [inline internal/kubehelper/client.go:18]: Sorry, I just realized… the user can totally provide this multiple times.
```
$ kubectl --kubeconfig /tmp/foo --kubeconfig ~/.kube/config config current-context
rancher-desktop
```
Yes, that's dumb… but quite possible if this was a non-interactive script.  It appears to take the _last_ `--kubeconfig` value.

**Review by mook-as — CHANGES_REQUESTED** [review]

File: internal/kubehelper/client.go (hunk 2 above)
Comment (jandubois) [reply internal/kubehelper/client.go]: Thanks, fixed by removing the `break` statements

File: internal/kubehelper/client.go [hunk 3]
```diff
@@ -11,8 +12,19 @@ import (
 
 func createKubeClient(timeout int64) (*kubernetes.Clientset, error) {
 	var cliKubeconfig string
-	flag.StringVar(&cliKubeconfig, "kubeconfig", "", "absolute path to the kubeconfig file")
-	flag.Parse()
+	for i := 1; i < len(os.Args)-1; i++ {
```
Comment (mook-as) [inline internal/kubehelper/client.go:15]: Will this catch `--kubeconfig=foo` being the last argument? I assume that `kubectl get pods --kubeconfig=/dev/null` is a valid command?

Was actually thinking about the `cliKubeconfig = os.Args[i+1]` two lines down, but that's safe because of this…

**Review by mook-as — CHANGES_REQUESTED** [review]

File: internal/kubehelper/client.go (hunk 3 above)
Comment (jandubois) [reply internal/kubehelper/client.go]: > I assume that `kubectl get pods --kubeconfig=/dev/null` is a valid command?

I thought the global options have to be specified before the command verb/word, but I guess not.

Fixed, I think (famous last words alert!).

**Review by mook-as — APPROVED** [review]
LGTM.

**Comment by jandubois** [comment]
Sorry, last [force push](https://github.com/flavio/kuberlr/compare/17ed7b9c617226bfccb8fbd277019acdb0e13008..2d9cf530b906045e094a3d2afe0696570890cb8f) was just correcting a typo in a comment

**Comment by flavio** [comment]
Hello, I just got back from vacation. That's why I didn't interact on the PR earlier.

@jandubois, @mook-as thanks for the PRs and the review process. Everything looks good to me
